chore: Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,6 +17,16 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+      - name: Check Actor
+        if: github.actor != 'kohdice'
+        run: |
+          echo "${{ github.actor }} does not have permission to release."
+          exit 1
+      - name: Check Branch
+        if: github.ref != 'refs/heads/main'
+        run: |
+          echo "Cannot release from a branch other than the main branch. Executed branch: ${{ github.ref }}"
+          exit 1
       - name: Set up Go
         uses: actions/setup-go@v5
         with:
